name: マーカーの通報
description: 不適切なマーカーを管理者に報告します
title: "[report] マーカーの通報"
labels: ["loca:report"]
body:
  - type: input
    id: marker-id
    attributes:
      label: マーカーID
    validations:
      required: true
  - type: input
    id: video-url
    attributes:
      label: Youtube URL
  - type: textarea
    id: reasons
    attributes:
      label: 通報理由
    validations:
      required: true
  - type: textarea
    id: detail
    attributes:
      label: 詳細
      description: 任意
